### Ordinal Encoding is performed by two Ways , One is Scikit learn and the other is Map Function

In [1]:
import  pandas as pd
df = pd.DataFrame({"Size":["s", "m", "l", "xl", "s", "m", "l", "s", "s", "l", "xl", "m"]})
df

   Size
0     s
1     m
2     l
3    xl
4     s
5     m
6     l
7     s
8     s
9     l
10   xl
11    m

In [2]:
order_data = [["s", "m", "l", "xl"]]
from sklearn.preprocessing import  OrdinalEncoder
oe  = OrdinalEncoder(categories= order_data) # categories = auto  ho tou alphabetically order krta

In [3]:
oe.fit(df[["Size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [5]:
df["size_encode"] = oe.transform(df[["Size"]])

In [6]:
df

   Size  size_encode
0     s          0.0
1     m          1.0
2     l          2.0
3    xl          3.0
4     s          0.0
5     m          1.0
6     l          2.0
7     s          0.0
8     s          0.0
9     l          2.0
10   xl          3.0
11    m          1.0

###### Map function

In [10]:
order_data1 = {"s" : 5, "m":10, "l": 15, "xl":20}
df["size_encode1"]=df["Size"].map(order_data1)

In [11]:
df

   Size  size_encode  size_encode1
0     s          0.0             5
1     m          1.0            10
2     l          2.0            15
3    xl          3.0            20
4     s          0.0             5
5     m          1.0            10
6     l          2.0            15
7     s          0.0             5
8     s          0.0             5
9     l          2.0            15
10   xl          3.0            20
11    m          1.0            10

In [26]:
df = pd.read_csv("loan.csv")

In [27]:
df["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [28]:
en_data_order = [['Urban', 'Rural', 'Semiurban']]

In [ ]:
oen = OrdinalEncoder(categories=en_data_order)
df["Property_Area"] =oen.fit_transform(df[["Property_Area"]])

In [30]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2.0,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0.0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2.0,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2.0,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,0.0,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,0.0,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,2.0,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,2.0,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,1.0,N

In [33]:
df["Married"].unique()

array(['No', 'Yes'], dtype=object)

In [32]:
df["Married"] = df["Married"].fillna(df["Married"].mode()[0])

In [34]:
order_data2 = [['No', 'Yes']]

In [36]:
oen1 = OrdinalEncoder(categories=order_data2)
df["Married"] = oen1.fit_transform(df[["Married"]])

In [37]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,0.0,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2.0,Y
1,LP001003,Male,1.0,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0.0,N
2,LP001005,Male,1.0,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2.0,Y
3,LP001006,Male,1.0,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2.0,Y
4,LP001008,Male,0.0,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,0.0,0,Graduate,No,2900,0.0,71.0,360.0,1.0,0.0,Y
610,LP002979,Male,1.0,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,0.0,Y
611,LP002983,Male,1.0,1,Graduate,No,8072,240.0,253.0,360.0,1.0,2.0,Y
612,LP002984,Male,1.0,2,Graduate,No,7583,0.0,187.0,360.0,1.0,2.0,Y
613,LP002990,Female,0.0,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,1.0,N